### ISSUE TITLE
Auto scrolling feature on pages

### ISSUE THREAD

**Issue by jpcormack** [jpcormack/www#2]
Auto scroll needs to be working across all pages to scroll passed the jumbotron.

**Comment by TiggaBiscuit** [comment]
Solution found with JQuery and HTML coding - Will update files with necessary code later tonight.

**Comment by TiggaBiscuit** [comment]
Each page now has a button with an arrow still have to make the arrows dim when hovered over. Not sure how to do that at the moment.

**Comment by jpcormack** [comment]
I'll check the code for the nav bar as it does the same. Might be able to come up with a quick solution.

**Comment by TiggaBiscuit** [comment]
Okay, well the code I have works. 🌮

**Comment by jpcormack** [comment]
Nice, is it on your github? Also, need to roll back my repo 1 revision before this can be merged in.
