### ISSUE TITLE
New Logo & site colors

### ISSUE THREAD

**Issue by jpcormack** [jpcormack/www#5]
- New logo has to be applied to the site.
- A new base color is requested (The background color from the new logo) * Note: Designer needs to make new logo specifically for site (Current logo doesn't have consistent background color.
- Color for highlighted navbar need to be updated.

**Comment by TiggaBiscuit** [comment]
So has this been done/finalised because I know there's the new logo but what about the colours?

**Comment by jpcormack** [comment]
This was to make sure the logo and background colours were consistant. I think we can close this one off.
